[package]
name = "simplicity"
version = "0.1.0"
authors = ["Andrew Poelstra <apoelstra@wpsoftware.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ "bitcoin", "elements" ]
test-utils = ["simplicity_sys/test-utils"]

[lib]
name = "simplicity"
path = "src/lib.rs"

[dependencies]
bitcoin = { version = "0.29.2", optional = true }
bitcoin_hashes = "0.11"
byteorder = "1.3"
elements = { version = "0.21.1", optional = true }
miniscript = "9.0.0"
simplicity_sys = { version = "0.1.0", path = "./simplicity-sys" }

[dev-dependencies]
simplicity_sys = { version = "0.1.0", path = "./simplicity-sys", features = ["test-utils"] }