[package]
name = "simplicity-sys"
version = "0.2.0"
edition = "2021"
rust-version = "1.58.0"

[build-dependencies]
cc = "1.0.83"

[dependencies]
libc = "0.2"
hashes = { package = "bitcoin_hashes", version = "0.13" }

[features]
test-utils = []
